### PR TITLE
fix: adjust mobile menu and some refactor

### PR DESCRIPTION
**Pull request by CoutoDev**

### CODE REVIEW

**Comment by jonatanaxe** [comment]
@CoutoDev Thanks for the PR, Do I need to compile something else?
Hover is not working
https://fix-mobile-button.discorgento-com.pages.dev/

It's like this on my cell phone

image

**Comment by CoutoDev** [comment]
> @CoutoDev Thanks for the PR, Do I need to compile something else?
> Hover is not working
> https://fix-mobile-button.discorgento-com.pages.dev/
> 
> It's like this on my cell phone
> 
> image
> 

Weird, which cell phone do you have?

**Comment by jonatanaxe** [comment]
> > @CoutoDev Thanks for the PR, Do I need to compile something else?
> > Hover is not working
> > [fix-mobile-button.discorgento-com.pages.dev](https://fix-mobile-button.discorgento-com.pages.dev/)
> > It's like this on my cell phone
> > image
> 
> Weird, which cell phone do you have?

poco x5 pro

**Comment by jonatanaxe** [comment]
@CoutoDev Hover is also not working in Chrome

**Comment by jonatanaxe** [comment]
@CoutoDev I found the problem: it gives an error in the compilation because of & it doesn't accept

image

**Comment by jonatanaxe** [comment]
@CoutoDev  Could you have a smaller font for mobile devices with smaller screens?

**Review by jonatanaxe — APPROVED** [review]

**Review by maria-axe — APPROVED** [review]

**Pull request merged**
